### ISSUE TITLE
Error when running the grabber

### ISSUE THREAD

**Issue by Xelicto** [vesperlol/Vespy-Grabber-v2.0#6]
I complied the stubber and ran it, and I get this error while running it. The information also doesn't go to my webhook.

![image](https://user-images.githubusercontent.com/120069833/210395176-858ff57a-505b-482c-ad12-334895c04fe4.png)

**Comment by THECRAZEDPOTATTO** [comment]
No shit if it crashes its not going to send

**Comment by vesperlol** [comment]
> I complied the stubber and ran it, and I get this error while running it. The information also doesn't go to my webhook.
> 
> ![image](https://user-images.githubusercontent.com/120069833/210395176-858ff57a-505b-482c-ad12-334895c04fe4.png)

anonfiles is down

**Comment by Lbj88** [comment]
> > I complied the stubber and ran it, and I get this error while running it. The information also doesn't go to my webhook.
> > ![image](https://user-images.githubusercontent.com/120069833/210395176-858ff57a-505b-482c-ad12-334895c04fe4.png)
> 
> anonfiles is down

you should use gofile instead, or you could implement a system where if anonfiles is down it should use gofile instead.

**Comment by vesperlol** [comment]
> > > I complied the stubber and ran it, and I get this error while running it. The information also doesn't go to my webhook.
> > > ![image](https://user-images.githubusercontent.com/120069833/210395176-858ff57a-505b-482c-ad12-334895c04fe4.png)
> > 
> > 
> > anonfiles is down
> 
> you should use gofile instead, or you could implement a system where if anonfiles is down it should use gofile instead.

gofile changes their apis very often

**Comment by Lbj88** [comment]
I have also heard of people using the file.io api it seems decent

**Comment by Xelicto** [comment]
> 

who are you

**Comment by BuffDecompiler** [comment]
Your ip is blacklisted on anonfiles.com! use a vpn
