### ISSUE TITLE
Critical Issue

### ISSUE THREAD

**Issue by Freeze-sys** [vesperlol/Vespy-Grabber-v2.0#66]
Bro i cannot open vesper bro

**Comment by Freeze-sys** [comment]
Anytime i open, either a cmd appears then disappears or when i open cmd and put the py inside it doesnt run

**Comment by NSXC** [comment]
This is not a Critical Issue so don't mark it as such it is a you issue you should have asked for help. The answer for this is to change the ```pip install``` in the file to ```py -m pip install```

**Comment by Freeze-sys** [comment]
Then what is next?
